<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="expires" content="-1">
<title>WiFi login</title>
</head>
<body style="font-family:system-ui,sans-serif;text-align:center;padding:40px 16px">
{{-- Generated by the dashboard and downloaded by the router as login.html.
     $(...) are MikroTik hotspot variables, filled in by the router.
     One file serves every hotspot network on the router: $(server-name) picks the target. --}}
<form name="portal" action="{{ $fallback }}" method="get">
  <input type="hidden" name="mac" value="$(mac)">
  <input type="hidden" name="ip" value="$(ip)">
  <input type="hidden" name="link-login-only" value="$(link-login-only)">
  <input type="hidden" name="link-orig" value="$(link-orig)">
  <input type="hidden" name="chap-id" value="$(chap-id)">
  <input type="hidden" name="chap-challenge" value="$(chap-challenge)">
  <input type="hidden" name="error" value="$(error)">
  <input type="hidden" name="server-name" value="$(server-name)">
  <p id="opening">Opening the WiFi login page...</p>
  <noscript><input type="submit" value="Continue"></noscript>
</form>
@if ($plain)
{{-- Networks set to "Router's built-in page" --}}
<form name="plain" id="plain" action="$(link-login-only)" method="post" hidden style="max-width:320px;margin:0 auto;text-align:left">
  <h1 style="font-size:1.4rem">WiFi login</h1>
  <p style="color:#b42318">$(error)</p>
  <input type="hidden" name="dst" value="$(link-orig)">
  <input type="hidden" name="popup" value="true">
  <p><label>Username<br><input name="username" value="$(username)" autocomplete="username" style="width:100%;padding:8px"></label></p>
  <p><label>Password<br><input name="password" type="password" autocomplete="current-password" style="width:100%;padding:8px"></label></p>
  <p><button type="submit" style="padding:10px 18px">Log in</button></p>
</form>
@endif
<script>
var targets = {!! json_encode($targets, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!};
var target = targets["$(server-name)"];
if (target === undefined) target = {!! json_encode($fallback, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG) !!};
if (target) {
  document.portal.action = target;
  document.portal.submit();
} else {
  document.getElementById('opening').hidden = true;
  document.getElementById('plain').hidden = false;
}
</script>
</body>
</html>
