<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="expires" content="-1">
<title>WiFi login</title>
</head>
<body style="font-family:system-ui,sans-serif;text-align:center;padding:40px 16px">
{{-- Generated by the dashboard and downloaded by the router as login.html.
     $(...) are MikroTik hotspot variables, filled in by the router. --}}
<form name="portal" action="{{ $target }}" method="get">
  <input type="hidden" name="mac" value="$(mac)">
  <input type="hidden" name="ip" value="$(ip)">
  <input type="hidden" name="link-login-only" value="$(link-login-only)">
  <input type="hidden" name="link-orig" value="$(link-orig)">
  <input type="hidden" name="chap-id" value="$(chap-id)">
  <input type="hidden" name="chap-challenge" value="$(chap-challenge)">
  <input type="hidden" name="error" value="$(error)">
  <input type="hidden" name="server-name" value="$(server-name)">
  <p>Opening the WiFi login page...</p>
  <noscript><input type="submit" value="Continue"></noscript>
</form>
<script>document.portal.submit();</script>
</body>
</html>
